FROM pangeo/pangeo-notebook:2019.12.04

#RUN conda install conda
#RUN conda install -c conda-forge gdal
ADD .  /$CONDA_DIR/geonotebook
#ADD ./devops/docker/jupyter.sh /jupyter.sh

WORKDIR /$CONDA_DIR/geonotebook
#RUN conda install -c conda-forge gdal
RUN pip install -U -r prerequirements.txt . && \
    pip install -U -r requirements.txt && \
    conda install -c conda-forge gdal && \
    jupyter serverextension enable --py geonotebook --sys-prefix && \
    jupyter labextension enable --py geonotebook --sys-prefix 

#VOLUME /notebooks
#WORKDIR /notebooks
USER $NB_UID
#ENTRYPOINT ["/jupyter.sh"]
CMD ["jupyterhub", "--no-ssl", "--Spawner.notebook_dir=/$CONDA_DIR/geonotebook]
