FROM jupyter/base-notebook:lab-2.2.5
RUN sudo apt-get install docker-ce=19.03.3 -y
COPY --chown=jovyan:jovyan . /srv
RUN chown -R jovyan:jovyan && \
    /srv
RUN echo "Copying configuration files..." \
    && mv /srv/condarc.yml ${CONDA_DIR}/.condarc \
    && mv /srv/dask_config.yml ${CONDA_DIR}/etc/dask.yml
